name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./my-app

      - name: Build Next.js app
        run: npm run build && npm run export
        working-directory: ./my-app

      - name: Create .nojekyll file
        run: touch ./my-app/out/.nojekyll

      - name: Create CNAME file
        run: echo 'www.omarswe.com' > ./my-app/out/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-app/out
          publish_branch: gh-pages
